In [ ]:
import pandas as pd
import numpy as np

In [49]:
fdi = pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/FDI.csv')
nifty = pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/Nifty.csv')

In [50]:
# ---> Remove commas and convert to numeric (float)
cols_to_convert = ['Gross Purchase FII', 'Gross Sales FII', 'Net Purchase FII',
                   'Gross Purchase DII', 'Gross Sales DII', 'Net Purchase DII']

for col in cols_to_convert:
    fdi[col] = fdi[col].astype(str).str.replace(',', '', regex=True)  # ---> Remove commas
    fdi[col] = pd.to_numeric(fdi[col], errors='coerce')  # ---> Convert to float

# ---> Check data types after conversion
print(fdi.dtypes)

Unnamed: 0              int64
Date                   object
Gross Purchase FII    float64
Gross Sales FII       float64
Net Purchase FII      float64
Gross Purchase DII    float64
Gross Sales DII       float64
Net Purchase DII      float64
dtype: object

In [52]:
fdi['Net Net'] = fdi['Net Purchase FII']+fdi['Net Purchase DII']
fdi['# Net Net'] = fdi['Net Net'].shift(-1)
fdi['Change FDI']=fdi['Net Net']-fdi['# Net Net']
fdi['Change% FDI']= ((fdi['Change FDI']/fdi['# Net Net'])*100)

In [53]:
fdi.head()

,Unnamed: 0,Date,Gross Purchase FII,Gross Sales FII,Net Purchase FII,Gross Purchase DII,Gross Sales DII,Net Purchase DII,Net Net,# Net Net,Change FDI,Change% FDI
0,1,28-Feb-2025,39239.44,50878.46,-11639.02,28065.55,15756.92,12308.63,669.61,1170.55,-500.94,-42.795267
1,2,27-Feb-2025,19055.23,19611.79,-556.56,13530.17,11803.06,1727.11,1170.55,-498.32,1668.87,-334.899262
2,3,25-Feb-2025,12500.37,16029.47,-3529.10,11278.09,8247.31,3030.78,-498.32,-1101.05,602.73,-54.741383
3,4,24-Feb-2025,7905.53,14192.23,-6286.70,12552.14,7366.49,5185.65,-1101.05,-564.54,-536.51,95.034896
4,5,21-Feb-2025,10144.33,13593.48,-3449.15,12889.44,10004.83,2884.61,-564.54,596.09,-1160.63,-194.707175

In [58]:
nifty.head()

,Unnamed: 0,Index Name,Date,Open,Close,Previous day,Change pts
0,0,NIFTY 50,2025-03-03,22194.55,22119.30,22124.70,-5.40
1,1,NIFTY 50,2025-02-28,22433.40,22124.70,22545.05,-420.35
2,2,NIFTY 50,2025-02-27,22568.95,22545.05,22547.55,-2.50
3,3,NIFTY 50,2025-02-25,22516.45,22547.55,22553.35,-5.80
4,4,NIFTY 50,2025-02-24,22609.35,22553.35,22795.90,-242.55

In [ ]:
nifty.head()
nifty['NIFTY_Change%']=((nifty['Close']-nifty['Previous day']/nifty['Close'])*100
                        )

SyntaxError: invalid syntax (4125854170.py, line 2)

In [54]:

nifty['Date']=pd.to_datetime(nifty['Date'])

In [55]:
nifty.dtypes

Unnamed: 0               int64
Index Name              object
Date            datetime64[ns]
Open                   float64
Close                  float64
Previous day           float64
Change pts             float64
dtype: object

In [43]:
Main = pd.DataFrame()

In [44]:
Main = pd.merge(nifty[['Date', 'Change pts']], 
                fdi[['Date', 'Change']], 
                on='Date', 
                how='inner')

In [45]:
Main.head()

        Date  Change pts   Change
0 2025-02-28     -420.35  -500.94
1 2025-02-27       -2.50  1668.87
2 2025-02-25       -5.80   602.73
3 2025-02-24     -242.55  -536.51
4 2025-02-21     -117.25 -1160.63