In [2]:
import pandas as pd

In [19]:
od= pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/official_data.csv")
od.head(5)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,From Date,31/07/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,To Date,20/01/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equity P&L Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total Gross PnL,-1353.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
od.iloc[25]
od.shape

(67, 20)

In [31]:
od.iloc[25]

Date Range             Scrip Symbol
Unnamed: 1             Company Name
Unnamed: 2                 Quantity
Unnamed: 3            Avg Buy Price
Unnamed: 4                Buy Value
Unnamed: 5           Avg Sell Price
Unnamed: 6               Sell Value
Unnamed: 7                Gross PnL
Unnamed: 8                Brokerage
Unnamed: 9                      GST
Unnamed: 10    Exchange Service Tax
Unnamed: 11            Turnover Tax
Unnamed: 12            SEBI Charges
Unnamed: 13              Stamp Duty
Unnamed: 14                     STT
Unnamed: 15           Other Charges
Unnamed: 16            IPFT Charges
Unnamed: 17            Intraday PnL
Unnamed: 18                     NaN
Unnamed: 19                     NaN
Name: 25, dtype: object

In [32]:
od1 = od.iloc[25:67]
od1.head(5)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,GST,Exchange Service Tax,Turnover Tax,SEBI Charges,Stamp Duty,STT,Other Charges,IPFT Charges,Intraday PnL,NaN,NaN
26,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.57,0,4.26,0.14,2,18,0,0.14,-129.19,NaN,NaN
27,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,2.96,0,1.47,0.05,1,6,0,0.05,-117.44,NaN,NaN
28,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,3.07,0,1.53,0.05,1,6,0,0.05,-194.84,NaN,NaN
29,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,1.53,0,0.76,0.03,0,3,0,0.03,-210.51,NaN,NaN

In [34]:
od1['tax']=od1.iloc[:,9:17].sum(axis=1)
od1

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_89883/4254156535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  od1['tax']=od1.iloc[:,9:17].sum(axis=1)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,tax
25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,GST,...,Turnover Tax,SEBI Charges,Stamp Duty,STT,Other Charges,IPFT Charges,Intraday PnL,NaN,NaN,GSTExchange Service TaxTurnover TaxSEBI Charge...
26,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.57,...,4.26,0.14,2,18,0,0.14,-129.19,NaN,NaN,8.5704.260.1421800.14
27,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,2.96,...,1.47,0.05,1,6,0,0.05,-117.44,NaN,NaN,2.9601.470.051600.05
28,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,3.07,...,1.53,0.05,1,6,0,0.05,-194.84,NaN,NaN,3.0701.530.051600.05
29,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,1.53,...,0.76,0.03,0,3,0,0.03,-210.51,NaN,NaN,1.5300.760.030300.03
30,M&M,MAHINDRA & MAHINDRA LTD,9,3133.96,28205.65,3122.1,28098.9,-106.75,16.89,3.36,...,1.67,0.06,1,7,0,0.06,-136.79,NaN,NaN,3.3601.670.061700.06
31,TRENT,TRENT LTD,2,6600.2,13200.4,6714.4,13428.8,228.4,7.99,1.59,...,0.79,0.03,0,3,0,0.03,214.98,NaN,NaN,1.5900.790.030300.03
32,TITAN,TITAN COMPANY LIMITED,7,3525.45,24678.15,3562.8,24939.6,261.45,14.89,2.96,...,1.47,0.05,1,6,0,0.05,235.02,NaN,NaN,2.9601.470.051600.05
33,LT,LARSEN & TOUBRO LTD.,7,3651.45,25560.15,3651.41,25559.85,-0.3,15.34,3.05,...,1.52,0.05,1,6,0,0.05,-27.31,NaN,NaN,3.0501.520.051600.05
34,TATAMOTORS,TATA MOTORS LIMITED,30,774.5,23235,768.85,23065.5,-169.5,13.89,2.76,...,1.38,0.05,1,6,0,0.05,-194.62,NaN,NaN,2.7601.380.051600.05
35,NTPC,NTPC LTD,65,386.6,25129,385.1,25031.5,-97.5,15.05,2.99,...,1.49,0.05,1,6,0,0.05,-124.13,NaN,NaN,2.9901.490.051600.05
36,ABFRL,ADITYA BIRLA FASHION & RT,100,306.6,30660,301.1,30110,-550,18.23,3.63,...,1.8,0.06,0.95,7.6,0,0.06,-582.33,NaN,NaN,3.6301.80.060.957.600.06
37,TATAMOTORS,TATA MOTORS LIMITED,2,809.83,1619.65,810.38,1620.75,1.1,0.97,0.2,...,0.12,0,0.05,0.4,0,0,-0.64,NaN,NaN,0.200.1200.050.400
38,TATASTEEL,TATA STEEL LIMITED,200,155.78,31156,155.12,31024,-132,18.65,3.71,...,1.85,0.06,1,8,0,0.06,-165.33,NaN,NaN,3.7101.850.061800.06
39,WIPRO,WIPRO LTD,80,572.5,45800,571.05,45684,-116,27.45,5.46,...,2.72,0.09,1,11,0,0.09,-163.81,NaN,NaN,5.4602.720.0911100.09
40,TECHM,TECH MAHINDRA LIMITED,25,1732.6,43314.95,1709.03,42725.85,-589.1,25.81,5.14,...,2.56,0.09,1,11,0,0.09,-634.77,NaN,NaN,5.1402.560.0911100.09
41,RELIANCE,RELIANCE INDUSTRIES LTD,12,2721.96,32663.55,2727.9,32734.8,71.25,19.62,3.9,...,1.94,0.07,0.98,8.17,0,0.07,36.5,NaN,NaN,3.901.940.070.988.1700.07
42,TATAMOTORS,TATA MOTORS LIMITED,55,896.5,49307.5,891.4,49027,-280.5,29.5,5.99,...,3.69,0.1,1.57,12.72,0,0,-334.07,NaN,NaN,5.9903.690.11.5712.7200
43,HDFCLIFE,HDFC LIFE INS CO LTD,65,743.05,48298.25,746.15,48499.55,201.3,29.04,5.78,...,2.87,0.1,1.45,12.1,0,0.1,149.86,NaN,NaN,5.7802.870.11.4512.100.1
44,LT,LARSEN & TOUBRO LTD.,10,3578.85,35788.5,3584.45,35844.5,56,21.49,4.28,...,2.13,0.07,1,9,0,0.07,17.96,NaN,NaN,4.2802.130.071900.07
45,INFY,INFOSYS LIMITED,20,1963.45,39269,1974.02,39480.35,211.35,23.62,4.7,...,2.34,0.08,1,10,0,0.08,169.53,NaN,NaN,4.702.340.0811000.08
46,MAZDOCK,MAZAGON DOCK SHIPBUIL LTD,3,4340.9,13022.7,4336.62,13009.85,-12.85,7.81,1.55,...,0.77,0.03,0,3,0,0.03,-26.04,NaN,NaN,1.5500.770.030300.03
47,SOUTHBANK,THE SOUTH INDIAN BANK LTD,2100,23.97,50337,24.02,50442,105,30.23,6.02,...,2.99,0.1,1.48,12.38,0,0.1,51.7,NaN,NaN,6.0202.990.11.4812.3800.1
48,APOLLO,APOLLO MICRO SYSTEMS LTD,500,101.11,50555,100.83,50415.29,-139.71,30.29,6.03,...,3,0.1,1.52,12.62,0,0.1,-193.37,NaN,NaN,6.03030.11.5212.6200.1
49,LT,LARSEN & TOUBRO LTD.,14,3540,49560,3555.1,49771.4,211.4,29.8,5.93,...,2.95,0.1,1,12,0,0.1,159.52,NaN,NaN,5.9302.950.111200.1
50,ADANIENT,ADANI ENTERPRISES LIMITED,6,3130.8,18784.8,3171.25,19027.5,242.7,11.34,2.26,...,1.12,0.04,1,5,0,0.04,221.9,NaN,NaN,2.2601.120.041500.04
51,TCS,TATA CONSULTANCY SERV LT,20,4266.85,85337.05,4285.87,85717.3,380.25,51.32,10.21,...,5.08,0.17,3,21,0,0.17,289.29,NaN,NaN,10.2105.080.1732100.17
52,OLAELEC,OLA ELECTRIC MOBILITY LTD,1,101.3,101.3,101.26,101.26,-0.04,0.06,0.01,...,0.01,0,0,0,0,0,-0.12,NaN,NaN,0.0100.0100000
53,OFSS,ORACLE FIN SERV SOFT LTD.,3,11714,35142,11685.65,35056.95,-85.05,21.06,4.21,...,2.26,0.07,1,9,0,0,-122.65,NaN,NaN,4.2102.260.071900
54,OFSS,ORACLE FIN SERV SOFT LTD.,6,11352.74,68116.45,11288.68,67732.05,-384.4,40.75,8.15,...,4.37,0.14,2,17,0,0,-456.81,NaN,NaN,8.1504.370.1421700
55,TATAMOTORS,TATA MOTORS LIMITED,16,1082.45,17319.2,1077.95,17247.2,-72,10.37,2.07,...,1.11,0.03,1,4,0,0,-90.59,NaN,NaN,2.0701.110.031400
56,TATAMOTORS,TATA MOTORS LIMITED,16,1086.05,17376.8,1085.3,17364.8,-12,10.42,2.08,...,1.12,0.03,1,4,0,0,-30.66,NaN,NaN,2.0801.120.031400
57,TATAMOTORS,TATA MOTORS LIMITED,16,1086.65,17386.4,1088.95,17423.2,36.8,10.44,2.09,...,1.12,0.03,1,4,0,0,18.12,NaN,NaN,2.0901.120.031400
58,TATAMOTORS,TATA MOTORS LIMITED,16,1091.55,17464.8,1092.25,17476,11.2,10.48,2.1,...,1.13,0.04,1,4,0,0,-7.54,NaN,NaN,2.101.130.041400
59,TATAMOTORS,TATA MOTORS LIMITED,17,1098.5,18674.5,1086.7,18473.9,-200.6,11.14,2.23,...,1.2,0.04,1,5,0,0,-221.2,NaN,NaN,2.2301.20.041500
60,TATAMOTORS,TATA MOTORS LIMITED,17,1050,17849.95,1058.3,17991.1,141.15,10.75,2.15,...,1.15,0.04,1,4,0,0,122.06,NaN,NaN,2.1501.150.041400
61,TATAMOTORS,TATA MOTORS LIMITED,34,1059.88,36035.75,1063.29,36152,116.25,21.66,4.33,...,2.32,0.07,1,9,0,0,77.86,NaN,NaN,4.3302.320.071900
62,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,2.19,...,1.18,0.04,1,5,0,0,-108.79,NaN,NaN,2.1901.180.041500
63,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,2.38,...,1.28,0.04,1,5,0,0,-190.71,NaN,NaN,2.3801.280.041500
64,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,2.46,...,1.32,0.04,1,5,0,0,-148,NaN,NaN,2.4601.320.041500
65,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,2.27,...,1.22,0.04,1,5,0,0,190.61,NaN,NaN,2.2701.220.041500
66,Total,NaN,NaN,NaN,1224006.1,NaN,1222652.33,-1353.77,733.99,146.35,...,75.06,2.47,41,302.99,0,1.72,-2657.35,NaN,NaN,146.35075.062.4741302.9901.72